"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.formRouter = void 0;
const express_1 = require("express");
const career_controller_js_1 = require("../controllers/career.controller.js");
const join_us_controller_js_1 = require("../controllers/join-us.controller.js");
const become_controller_js_1 = require("../controllers/become.controller.js");
const help_controller_js_1 = require("../controllers/help.controller.js");
const service_controller_js_1 = require("../controllers/service.controller.js");
const enquiry_controller_js_1 = require("../controllers/enquiry.controller.js");
const brochure_controller_js_1 = require("../controllers/brochure.controller.js");
exports.formRouter = (0, express_1.Router)();
exports.formRouter.post("/careers", career_controller_js_1.careerFormController);
exports.formRouter.post("/join-us", join_us_controller_js_1.joinUsController);
exports.formRouter.post("/become-certified", become_controller_js_1.becomeController);
exports.formRouter.post("/help", help_controller_js_1.helpController);
exports.formRouter.post("/services", service_controller_js_1.serviceController);
exports.formRouter.post("/enquiry", enquiry_controller_js_1.enquiryController);
exports.formRouter.post("/send-brochure", brochure_controller_js_1.brochureController);
